docs: ajout d'infos à propos de SFTP et SCP
club-1/docs pull request #114
Opened 2022-07-07 12:39 UTC by n-peugnet

Closes https://github.com/club-1/docs/issues/69

À merger en mode `Squash and merge`.

2022-07-10 18:56 UTC, vincent-peugnet requested changes
je pense qu'il y a une coquille

2022-07-10 18:56 UTC, vincent-peugnet commented on services/ssh.md
> +   Il ainsi entièrement chiffré, et donc comparable à {term}`FTPS`,
il manque un "est" ou un truc du genre

2022-07-10 18:56 UTC, vincent-peugnet commented on services/ssh.md
> +   mais il offre plus de fonctionnalités (e.g. l'affichage des propriétaires d'un fichier). ---
il peut y avoir plusieurs proprios pour un seul fichier sous UNIX ?

2022-07-10 20:43 UTC, n-peugnet commented on services/ssh.md
> +   Il ainsi entièrement chiffré, et donc comparable à {term}`FTPS`,
bien vu !

2022-07-10 20:44 UTC, n-peugnet commented on services/ssh.md
> +   mais il offre plus de fonctionnalités (e.g. l'affichage des propriétaires d'un fichier). ---
par "propriétaires" d'un fichier j'imaginais "propriétaire et groupe" de ce fichier

2022-07-23 11:22 UTC, vincent-peugnet approved these changes

2022-07-23 11:22 UTC, merged