tuto premiere co ssh
club-1/docs pull request #192
Opened 2022-11-25 12:03 UTC by vincent-peugnet

- nouveau term : fichier/dossier cache

2022-11-25 19:46 UTC, n-peugnet requested changes
Un premier set de modifications. Ensuite il y aura les fautes d’orthographe.

2022-11-25 19:46 UTC, n-peugnet commented on glossaire.md
> +   Cela sert souvent pour masquer des paramètres peu utiles au quotidien.
```suggestion
   Cela sert souvent à masquer des paramètres peu utiles au quotidien.
```

2022-11-25 19:46 UTC, n-peugnet commented on glossaire.md
> +   souvent avec le raccourci clavier {kbd}`CTRL` + {kbd}`H`.
```suggestion
   souvent avec le raccourci clavier {kbd}`Ctrl` + {kbd}`H`.
```

2022-11-25 19:46 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +Pour effectuer cette connexion SSH nous allons utiliser la {term}`CLI` via **le terminal** ! 🥵
Pour compléter ce que j'ai dit plus haut.

```suggestion
Pour effectuer cette connexion SSH nous allons utiliser {term}`OpenSSH`.
Ce logiciel s'utilise en {term}`CLI`,
il est donc nécessaire d'ouvrir une fenêtre de **terminal** (`cmd` sur windows) ! 🥵
```

2022-11-25 19:46 UTC, n-peugnet commented on services/ssh.md
> +nécessaire d'ouvrir une fenêtre de terminal (`cmd` sur windows).
pour moi ça ça appartient plutôt au tuto. Si tu ne sais pas qu'il faut un terminal pour te connecter c'est qu'il faut suivre le tuto.

2022-11-25 19:46 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +
Je le mettrais plutôt après la copie du message.
```suggestion
```

2022-11-25 19:46 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +>     ED25519 key fingerprint is SHA256:t4m5ioK2DGyObdxh3ATIIKnbhm4EhCp1cfgQmogHd58.
j'enlèverais cette fingerprint qui est visiblement à même de varier.

```suggestion
>     ED25519 key fingerprint is SHA256:*********.
```

2022-11-25 19:46 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +
Et je changerais d'émoji :

```suggestion

> 😱 Houla ! Qu'est ce que c'est que ça ??

```

2022-11-25 19:46 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +
Ajout de l'instruction pour quitter ce message
```suggestion

En répondant `yes` à ce message on s'expose à une [attaque de l'homme du milieu](https://fr.wikipedia.org/wiki/Attaque_de_l%27homme_du_milieu).
Nous allons donc répondre `no` pour le moment.

```

2022-11-25 19:46 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +Cela permet de chiffrer ce qu'on lui envoie en étant sûr que seul le serveur pourra le déchiffrer.
J'ai revérifié et visiblement la clé est utilisée uniquement par comparaison : https://en.wikibooks.org/wiki/OpenSSH/Client_Configuration_Files#~/.ssh/known_hosts

```suggestion
Nous allons rajouter à votre appareil la **clef publique** du serveur CLUB1.
Cela permet de garantir l'authenticité des réponse du serveur et d'initialiser une connexion chiffrée.
De cette manière on est certains que l'on a bien affaire au serveur de CLUB1.

```

2022-11-27 09:35 UTC, vincent-peugnet commented on services/ssh.md
> +nécessaire d'ouvrir une fenêtre de terminal (`cmd` sur windows).
oki bah j'ai commité ces suggestion, c'est donc possible de supprimer ce passage

2022-11-28 12:04 UTC, n-peugnet approved these changes
Quelques corrections mais sinon je suis OK

2022-11-28 12:04 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +    │  ├─ 📄 known_host    👈
```suggestion
    │  └─ 📄 known_host    👈
```

2022-11-28 12:04 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +Si tout c'est bien passé,
```suggestion
Si tout s'est bien passé,
```

2022-11-28 12:04 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +Il faut ensuite entrer votre **mot de passe** CLUB1 (il est normal que le mot de passe ne s'affiche pas au moment de l'écriture).
Cette ligne devrait être déplacée à la fin. On ne devrait pas arriver jusqu'à l'invite de mot de passe ici en suivant les instructions

2022-11-28 12:04 UTC, n-peugnet commented on glossaire.md
> +   Il est possible de d'activer leur affichage si besoin,
```suggestion
   Il est possible d'activer leur affichage si besoin,
```

2022-11-28 12:04 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +Ne vous laissez pas impressioner par son interface déroutante,
```suggestion
Ne vous laissez pas impressionner par son interface déroutante,
```

2022-11-28 14:14 UTC, n-peugnet commented on tutos/premiere-connexion-ssh.md
> +Permet de voir ce qui se passe sur le serveur en se moment et à quel point les ressources sont utilisés.
```suggestion
Permet de voir ce qui se passe sur le serveur en ce moment et à quel point les ressources sont utilisées.
```

2022-11-28 14:27 UTC, merged