Ajout de la section "services ouverts", de la notice Matrix et quelques définitions
club-1/docs pull request #227
Opened 2023-03-16 00:12 UTC by n-peugnet

- docs: ajout d'une définition très simple de protocole
- docs: précision à propos des services réservés aux membres
- docs: ajout d'une définition de terminal
- docs: ajout services ouverts et notice de Matrix

2023-03-16 22:52 UTC, LeilaRenard requested changes

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +d'interdire l'accès aux utilisateurs qui ne sont pas inscris sur ce serveur en particulier.
```suggestion
d'interdire l'accès aux utilisateurs qui ne sont pas inscrits sur ce serveur en particulier.
```

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +et `club1.fr`, le serveur sur lequel elle a été crée et auxquel elle est ratachée.
```suggestion
et `club1.fr`, le serveur sur lequel elle a été créee et auquel elle est ratachée.
```

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +
Et element desktop sur linux ?

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +Par défault, seule les rooms du serveur local sont listés.
```suggestion
Par défaut, seules les rooms du serveur local sont listées.
```

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +
Est-ce qu'il ne faudrait pas  rajouter qu'en cas de chiffrement on ne peut pas revenir en arrière plus tard (je l'ai déjà fait et regretté) ?

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +
Est-ce qu'il faudrait pas  rajouter qu'en cas de chiffrement on ne peut pas revenir en arrière plus tard (je l'ai déjà fait et regretté) ?

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +Il est possible de formater son message, en selectionnant du texte sur la zone d'écriture de message,
```suggestion
Il est possible de formater son message, en sélectionnant du texte sur la zone d'écriture de message,
```

2023-03-16 22:52 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +Des mises à jours sont effectués régulièrement
```suggestion
Des mises à jour sont effectuées régulièrement
```

2023-03-16 22:59 UTC, n-peugnet commented on services-ouverts/matrix.md
> +mais on peut aussi préfèrer l'ambiance *fluffy* de [FluffyChat](https://fluffychat.im/en/)
```suggestion
mais on peut aussi préférer l'ambiance *fluffy* de [FluffyChat](https://fluffychat.im/)
```

2023-03-16 23:04 UTC, n-peugnet commented
Merci @LeilaRenard pour la relecture, j'avoue qu'à part quelques modifications de mise en forme je n'ai pas vraiment cherché à corriger les fautes de ce texte copié-collé.

2023-03-16 23:05 UTC, n-peugnet commented on services-ouverts/matrix.md
> +
je pense qu'on pourra voir plus tard. L'appli element desktop n'apporte pas grand chose par rapport à la version hébergée sur club1.fr. L'idée ici ça serait plus de recommander des clients natifs genre fractal ou neochat

2023-03-16 23:06 UTC, n-peugnet commented on services-ouverts/matrix.md
> +
Si c'est une bonne idée. Peut-être dans un bloc `{warning}` ?

2023-03-16 23:06 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +
okayz

2023-03-16 23:07 UTC, LeilaRenard commented on services-ouverts/matrix.md
> +
Oui ça me semble bien !

2023-03-17 11:37 UTC, n-peugnet commented on services-ouverts/matrix.md
> +
C'est fait !

2023-03-18 00:22 UTC, vincent-peugnet commented on services/index.md
> +Ils utilisent donc le même **identifiant** et le même **mot de passe** pour la connexion.
Je me demande si on peut pas faire un poil plus clair.
Voici un test à rediscuter.

```suggestion
L'accès à ces services nécessite d'être membre de CLUB1.
Pour s'y connecter il faut renseigner son identifiant et mot de passe liées à son compte CLUB1.
```

2023-03-18 20:21 UTC, n-peugnet commented on services/index.md
> +Ils utilisent donc le même **identifiant** et le même **mot de passe** pour la connexion.
On verra ça plus tard du coup. Tu feras une pull request par dessus celle-ci @vincent-peugnet.

2023-03-18 20:23 UTC, merged