faq : nouvelle entrée : nom de domaine externe
club-1/docs pull request #318
Opened 2024-11-17 12:19 UTC by vincent-peugnet

+ complète le terme Nom de Domaine

2024-11-22 08:56 UTC, n-peugnet commented
Pour l'instant je ne suis pas satisfait. Mais c'est vrai que c'est hyper galère à expliquer. Je vais tenter de faire une contre proposition bientôt.

2024-11-22 18:10 UTC, n-peugnet requested changes

2024-11-22 18:10 UTC, n-peugnet commented on faq.md
> +```
Du coup voilà ma proposition, j'ai un peu tout changé. Tu peux remodifier, mais je ne pense pas que ça soit une bonne idée de parler de niveau de domaine, parce que ce n'est pas forcément un domaine de niveau 2 que les particuliers louent.

````suggestion
**C'est possible**, cependant il y a une contrainte technique :
⚠️ Il est nécessaire d'utiliser **un sous-domaine de votre {term}`nom de domaine`**.

Par exemple, si vous possédez `crevette.com`,
il ne sera pas possible d'héberger le site `https://crevette.com` sur le serveur CLUB1.
Il faudra utiliser un sous domaine, tel que `https://www.crevette.com`.
(Ça peut être autre chose que `www`, mais c'est une convention pour le {term}`Web`)

Concrètement, il s'agit d'ajouter un enregistrement CNAME pour `www` pointant vers `club1.fr`.
Utiliser un CNAME permet de créer un {term}`alias` sur un nom de domaine plutôt que sur une {term}`adresse IP`.
C'est pratique dans notre cas, car l'adresse IP du serveur CLUB1 peut changer,
tandis que son nom de domaine ne changera pas.

```{tip}
Chez certains {term}`registraires <registraire>`,
il est possible de créer une redirection HTTP automatique
depuis votre nom de domaine vers le sous-domaine de votre choix.
```
````

2024-11-22 18:10 UTC, n-peugnet commented on glossaire.md
> +
Du coup je ne pense pas que ce soit utile de parler des niveaux ici, surtout qu'un sous-domaine n'est pas forcément un domaine de troisième niveau.

```suggestion
   En plus de ces informations, un domaine peut également avoir des sous domaines.
```

2024-11-23 00:00 UTC, vincent-peugnet commented
Trop bien ! J'ai kiffé ta version ! C'est bon pour moi !

2024-11-23 00:30 UTC, n-peugnet commented
Ok. Let's go, de toute façon c'est mieux que rien !

2024-11-23 00:30 UTC, n-peugnet approved these changes

2024-11-23 00:32 UTC, merged